"""Initial ListsLists schema."""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("username", sa.String(80), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.String(255)), sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("auth_source", sa.String(20), nullable=False, server_default="local"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("username"), sa.UniqueConstraint("email"))
    op.create_index("ix_users_username", "users", ["username"]); op.create_index("ix_users_email", "users", ["email"])
    op.create_table("lists", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("slug", sa.String(220), nullable=False, unique=True), sa.Column("description", sa.Text(), nullable=False), sa.Column("owner_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("visibility", sa.Enum("private","shared","unlisted","public", name="visibility"), nullable=False), sa.Column("default_sort", sa.JSON(), nullable=False), sa.Column("custom_metadata", sa.JSON(), nullable=False), sa.Column("archived", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_lists_name", "lists", ["name"]); op.create_index("ix_lists_slug", "lists", ["slug"], unique=True); op.create_index("ix_lists_owner_id", "lists", ["owner_id"]); op.create_index("ix_lists_archived", "lists", ["archived"])
    op.create_table("list_items", sa.Column("id", sa.String(36), primary_key=True), sa.Column("list_id", sa.String(36), sa.ForeignKey("lists.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(240), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("quantity", sa.Float(), nullable=False), sa.Column("unit", sa.String(40), nullable=False), sa.Column("category", sa.String(120)), sa.Column("tags", sa.JSON(), nullable=False), sa.Column("storage_location", sa.String(240)), sa.Column("usage_context", sa.String(240)), sa.Column("is_required", sa.Boolean(), nullable=False), sa.Column("notes", sa.Text(), nullable=False), sa.Column("position", sa.Integer(), nullable=False), sa.Column("referenced_list_id", sa.String(36), sa.ForeignKey("lists.id", ondelete="RESTRICT")), sa.Column("identity_key", sa.String(160)), sa.Column("conditional_requirements", sa.JSON(), nullable=False), sa.Column("custom_metadata", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    for name, cols in [("ix_items_list_position", ["list_id","position"]),("ix_list_items_list_id",["list_id"]),("ix_list_items_category",["category"]),("ix_list_items_referenced_list_id",["referenced_list_id"]),("ix_list_items_identity_key",["identity_key"])]: op.create_index(name, "list_items", cols)
    op.create_table("item_dependencies", sa.Column("id", sa.String(36), primary_key=True), sa.Column("item_id", sa.String(36), sa.ForeignKey("list_items.id", ondelete="CASCADE"), nullable=False), sa.Column("depends_on_item_id", sa.String(36), sa.ForeignKey("list_items.id", ondelete="CASCADE"), nullable=False), sa.Column("condition", sa.String(240)), sa.Column("required", sa.Boolean(), nullable=False, server_default=sa.true()), sa.UniqueConstraint("item_id","depends_on_item_id")); op.create_index("ix_item_dependencies_item_id","item_dependencies",["item_id"]); op.create_index("ix_item_dependencies_depends_on_item_id","item_dependencies",["depends_on_item_id"])
    op.create_table("list_shares", sa.Column("id", sa.String(36), primary_key=True), sa.Column("list_id", sa.String(36), sa.ForeignKey("lists.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.Enum("editor","viewer",name="sharerole"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("list_id","user_id")); op.create_index("ix_list_shares_list_id","list_shares",["list_id"]); op.create_index("ix_list_shares_user_id","list_shares",["user_id"])
    op.create_table("export_profiles", sa.Column("id",sa.String(36),primary_key=True), sa.Column("owner_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False), sa.Column("name",sa.String(160),nullable=False), sa.Column("format",sa.String(10),nullable=False), sa.Column("options",sa.JSON(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_export_profiles_owner_id","export_profiles",["owner_id"])
    op.create_table("password_reset_tokens", sa.Column("id",sa.String(36),primary_key=True), sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False), sa.Column("token_hash",sa.String(64),nullable=False,unique=True), sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False), sa.Column("used_at",sa.DateTime(timezone=True)), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_password_reset_tokens_user_id","password_reset_tokens",["user_id"]); op.create_index("ix_password_reset_tokens_token_hash","password_reset_tokens",["token_hash"],unique=True)
    op.create_table("audit_events", sa.Column("id",sa.String(36),primary_key=True), sa.Column("actor_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")), sa.Column("action",sa.String(120),nullable=False), sa.Column("target_type",sa.String(50),nullable=False), sa.Column("target_id",sa.String(36)), sa.Column("details",sa.JSON(),nullable=False), sa.Column("ip_address",sa.String(64)), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    for col in ["actor_id","action","target_type","target_id","created_at"]: op.create_index(f"ix_audit_events_{col}","audit_events",[col])
    op.create_table("app_settings", sa.Column("key", sa.String(80), primary_key=True), sa.Column("value", sa.JSON(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))


def downgrade():
    for table in ["app_settings","audit_events","password_reset_tokens","export_profiles","list_shares","item_dependencies","list_items","lists","users"]: op.drop_table(table)
